apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kasten-tls
  namespace: kasten-io
spec:
  secretName: kasten-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kasten.mcourcy-gke.kastenevents.com
  dnsNames:
  - kasten.mcourcy-gke.kastenevents.com